# Generated by Django 5.2.9 on 2026-01-29 12:17

import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension # <--- AGGIUNTO

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(), # <--- AGGIUNTO COME PRIMA OPERAZIONE
        migrations.CreateModel(
            name='CatalogedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='catalog/')),
                ('original_name', models.CharField(max_length=255)),
                ('ai_description', models.TextField(blank=True)),
                ('generated_tags', models.JSONField(default=list)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cataloged Images',
                'db_table': 'cataloged_images',
            },
        ),
    ]