# Generated by Django 5.2.9 on 2026-01-29 16:36

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feature_featurevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogedimage',
            name='ai_description',
        ),
        migrations.RemoveField(
            model_name='catalogedimage',
            name='embedding_vector',
        ),
        migrations.RemoveField(
            model_name='catalogedimage',
            name='generated_tags',
        ),
        migrations.AddField(
            model_name='catalogedimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ImageDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('ai_description', models.TextField(blank=True)),
                ('generated_tags', models.JSONField(blank=True, default=list)),
                ('is_reference', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('bounding_box', models.JSONField(help_text='Formato: [ymin, xmin, ymax, xmax]')),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='api.catalogedimage')),
            ],
            options={
                'verbose_name_plural': 'Image Detections',
                'db_table': 'image_detections',
            },
        ),
    ]
